export default [
  {
    id: 0,
    music: 'Disney Opening',
    movie: '디즈니 오프닝',
    time: '0:00',
    cover: './image/disney.jpg',
  },
  {
    id: 1,
    music: "You're Welcome",
    movie: '모아나',
    time: '0:14',
    cover: './image/moana.jpg',
  },
  {
    id: 2,
    music: 'Let It Go',
    movie: '겨울왕국',
    time: '2:53',
    cover: './image/prozen.jpg',
  },
  {
    id: 3,
    music: "How Far i'll Go",
    movie: '모아나',
    time: '6:32',
    cover: './image/moana.jpg',
  },
  {
    id: 4,
    music: 'Try everything',
    movie: '주토피아',
    time: '9:00',
    cover: './image/zootopia.jpg',
  },
  {
    id: 5,
    music: 'Under the Sea',
    movie: '인어공주',
    time: '12:17',
    cover: './image/marine.jpg',
  },
  {
    id: 6,
    music: 'Speechless',
    movie: '알라딘',
    time: '15:27',
    cover: './image/alradin.jpg',
  },
  {
    id: 7,
    music: 'Part of Your World',
    movie: '인어공주',
    time: '18:43',
    cover: './image/marine.jpg',
  },
  {
    id: 8,
    music: 'See The Light',
    movie: '라푼젤',
    time: '21:51',
    cover: './image/tangled.jpg',
  },
  {
    id: 9,
    music: 'Can you feel the love tonight',
    movie: '라이온킹',
    time: '25:28',
    cover: './image/rionking.jpg',
  },
  {
    id: 10,
    music: 'Whole New World ',
    movie: '알라딘',
    time: '28:25',
    cover: './image/alradin.jpg',
  },
  {
    id: 11,
    music: 'Beauty and the Beast',
    movie: '미녀와 야수',
    time: '31:13',
    cover: './image/beauty.jpg',
  },
  {
    id: 12,
    music: 'Arabian Nights',
    movie: '알라딘',
    time: '34:00',
    cover: './image/alradin.jpg',
  },
  {
    id: 13,
    music: 'Remember me',
    movie: '코코',
    time: '37:02',
    cover: './image/coco.jpg',
  },
  {
    id: 14,
    music: 'Do You Want To Build A Snowman? ',
    movie: '겨울왕국',
    time: '39:47',
    cover: './image/prozen.jpg',
  },
  {
    id: 15,
    music: "You've Got a Friend In me",
    movie: '토이스토리',
    time: '41:52',
    cover: './image/toystory.jpg',
  },
];
